# project:
#   file: SwiftSourceryTemplates/SwiftSourceryTemplates.xcodeproj
#   target:
#     name: SwiftSourceryTemplates
#     module: SwiftSourceryTemplates
sources:
  - SwiftSourceryTemplates
templates:
  - ../../templates/TypeErase.swifttemplate
output:
  SwiftSourceryTemplates/SwiftSourceryTemplates/Generated
args:
  import:
    - RxSwift
  excludedSwiftLintRules:
    - function_body_length
    - line_length
    - vertical_whitespace
cacheBasePath:
  .SourceryCache
