project:
  file: SwiftSourceryTemplates/SwiftSourceryTemplates.xcodeproj
  target:
    name: SwiftSourceryTemplates
    module: SwiftSourceryTemplates
templates:
  - ../../templates/Mocks.swifttemplate
output:
  SwiftSourceryTemplates/SwiftSourceryTemplatesTests/Mocks
args:
  testable:
    - SwiftSourceryTemplates
  import:
    - RxSwift
    - RxBlocking
    - RxTest
    - Alamofire
  excludedSwiftLintRules:
    - force_cast
    - function_body_length
    - line_length
    - vertical_whitespace
