source 'https://cdn.cocoapods.org/'

workspace 'SwiftSourceryTemplates.xcworkspace'

target 'SwiftSourceryTemplates' do
    platform :osx, '10.13'
    use_frameworks!
    project 'SwiftSourceryTemplates/SwiftSourceryTemplates.xcodeproj'

    pod 'Alamofire', '~> 4.0'
    pod 'RxSwift'
    pod 'Sourcery', :git => 'https://github.com/krzysztofzablocki/Sourcery', :tag => '2.1.2'

    target 'SwiftSourceryTemplatesTests' do
      platform :osx, '10.13'
      inherit! :search_paths

      pod 'RxBlocking'
      pod 'RxTest'
    end
end
