# package:
#   path: ../.. #${SOURCERY_PACKAGE_PATH}
#   target:
#     - ExampleProjectSpm
#     - ExampleProjectSpmTests
sources:
  - ${SOURCERY_TARGET_ExampleProjectSpm}
  - ${SOURCERY_TARGET_ExampleProjectSpm_DEP_RIBs_MODULE_RIBs}
  - ${SOURCERY_TARGET_ExampleProjectSpmTests}/SourceryAnnotations
output: ${SOURCERY_OUTPUT_DIR}
templates:
  - ../../../../templates/Mocks.swifttemplate
args:
  testable:
    - ExampleProjectSpm
  import:
    - RIBs
    - RxSwift
    - RxBlocking
    - RxTest
    - Alamofire
    - UIKit
  excludedSwiftLintRules:
    - force_cast
    - function_body_length
    - line_length
    - vertical_whitespace
