# package:
#   path: ../.. #${SOURCERY_PACKAGE_PATH}
#   target:
#     - ExampleProjectSpm
#     - ExampleProjectSpmTests
sources:
  - ${SOURCERY_TARGET_ExampleProjectSpm}
  - ${SOURCERY_TARGET_ExampleProjectSpm_DEP_RIBs_MODULE_RIBs}
  - ${SOURCERY_TARGET_ExampleProjectSpmTests}/SourceryAnnotations
output: ${SOURCERY_OUTPUT_DIR}
templates:
  - ${GIT_ROOT}/templates/Mocks.swifttemplate
args:
  testable:
    - ExampleProjectSpm
  import:
    - Alamofire
    - Combine
    - RIBs
    - RxBlocking
    - RxSwift
    - RxTest
    - SwiftUI
    - UIKit
  excludedSwiftLintRules:
    - force_cast
    - function_body_length
    - line_length
    - vertical_whitespace
