# package:
#   path: ../.. #${SOURCERY_PACKAGE_PATH}
#   target:
#     - ExampleProjectSpm
sources:
  - ${SOURCERY_TARGET_ExampleProjectSpm}
output: ${SOURCERY_OUTPUT_DIR}
templates:
  - ${GIT_ROOT}/templates/TypeErase.swifttemplate
args:
  import:
    - RIBs
    - RxSwift
    - UIKit
  excludedSwiftLintRules:
    - function_body_length
    - line_length
    - vertical_whitespace
